# Generated by Django 4.1 on 2024-05-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatModel',
        ),
    ]
