# Generated by Django 4.2 on 2024-05-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_is_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='is_friend',
            field=models.IntegerField(choices=[('false', 'false'), ('pending', 'pending'), ('true', 'true')], default='false'),
        ),
    ]
