# Generated by Django 4.1 on 2024-04-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailconfirmationmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailConfirmationModel',
            new_name='UserSignupEmailSenderModel',
        ),
    ]
